sudo: required
services:
  - docker

env:
  matrix:
    - TEST=test
    - TEST=test-101

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script: 
  - docker-compose run --rm $TEST
