version: "3.4"

services:
  hello:
    image: softwareag/hello:10.3
    build:
      context: .
      args:
        - BUILDER_IMAGE=store/softwareag/commandcentral-builder:10.3  # Use the latest available builder image
        - NODE_IMAGE=store/softwareag/commandcentral-node:10.3 # Use node image for the target release
        - REPO_PRODUCT_URL=https://sdc.softwareag.com/dataservewebM103/repository # product repository must match target release
        - REPO_FIX_URL=https://sdc.softwareag.com/updates/prodRepo # fix repository must have fixes for the target release
        - REPO_USERNAME=${EMPOWER_USR} # repo credentials
        - REPO_PASSWORD=${EMPOWER_PSW} # repo credentials
        - BASE_IMAGE=centos:7 # base image
        # - BASE_IMAGE=openjdk:8-jre-slim
        - __hello_name=Docker103 # pass parameter values to the template at build time
    ports:
      - 8092

  hello-101:
    image: softwareag/hello:10.1
    build:
      context: .
      args:
        - BUILDER_IMAGE=store/softwareag/commandcentral-builder:10.3 # Use the latest available builder image
        - NODE_IMAGE=store/softwareag/commandcentral:10.1-node # Use node image for the target release
        - REPO_PRODUCT_URL=https://sdc.softwareag.com/dataservewebM101/repository # product repository must match target release
        - REPO_FIX_URL=https://sdc.softwareag.com/updates/prodRepo # fix repository must have fixes for the target release
        - REPO_USERNAME=${EMPOWER_USR} # repo credentials
        - REPO_PASSWORD=${EMPOWER_PSW} # repo credentials
        - BASE_IMAGE=centos:7 # base image
        # - BASE_IMAGE=openjdk:8-jre-slim
        - __hello_name=Docker101 # pass parameter values to the template at build time
    ports:
      - 8092

  test:
    image: store/softwareag/commandcentral-client:10.3
    command: sagcc list inventory products --wait-for-cc --wait 120 -e 10.3
    environment:
      - CC_SERVER=http://hello:8092/spm
    depends_on:
      - hello

  test-101:
    image: store/softwareag/commandcentral-client:10.3
    command: sagcc list inventory products --wait-for-cc --wait 120 -e 10.1
    environment:
      - CC_SERVER=http://hello-101:8092/spm
    depends_on:
      - hello-101
