ARG RELEASE=10.1
FROM simple/msc:$RELEASE as builder
FROM unmanaged/msc:$RELEASE as base

# add SPM and CLI binaries
COPY --from=builder $SAG_HOME/profiles/SPM/ $SAG_HOME/profiles/SPM/
COPY --from=builder $SAG_HOME/CommandCentral/client/ $SAG_HOME/CommandCentral/client/

# CLI support
ENV CC_CLI_HOME=$SAG_HOME/CommandCentral/client
ENV PATH=$PATH:$CC_CLI_HOME/bin

# SPM ports
EXPOSE 8092 8093
